### ISSUE TITLE
Milestone 2 - Workplan

### ISSUE THREAD

**Issue by aylapear** [UBC-MDS/seating_pref#12]
**Data & Survey**
- [x] download survey data
- [x] make private github repo
- [x] clean data
- [x] close survey

**EDA**
- [x] gender (Socorro)
- [x] engagement (George)
- [x] seating preference  (Bonnie)
- [x] competitiveness (Ayla)

**Other**
- [x] compile EDA 
- [x] update contributing doc
- [x] review

**Comment by GeorgeJJW** [comment]
Addressed with #14
