### ISSUE TITLE
Milestone 3 - workplan

### ISSUE THREAD

**Issue by aylapear** [UBC-MDS/seating_pref#17]
**Model Plan**
- use binomial glm
- [x] look at effects of removing duplicates (George)

**Report**
- [x]  framework of the report in .Rmd
- [x] Variable section & Discussion (Socorro)
   - include table for each variable
- [x] Additive model (Ayla)
   - t-test, p-value, betas, CI
- [x] Interaction model (Bonnie)
   - t-test, p-value, betas, CI
- [x] compiling everything including adding in EDA and proposal (George)
- [x] review

**Comment by GeorgeJJW** [comment]
Addressed with #23
